Fix unhealthy container
lidofinance/lido-oracle pull request #400
Opened 2023-10-03 21:37 UTC by F4ever

2023-10-04 06:25 UTC, vgorkavenko requested changes
It shouldn't be like this. `Pulse` is needed for using by docker healthcheck because it is like a simple approach to ensure that everything is fine with application, so it shouldn't be requested inside a code (otherwise we obtain a recursive dependence).

Let's fix `Dockerfile` and nothing else:
From:
```
CMD curl -f http://localhost:$HEALTHCHECK_SERVER_PORT/healthcheck || exit 1
```
To:
```
CMD curl -f http://localhost:$HEALTHCHECK_SERVER_PORT/pulse || exit 1
```

2023-10-04 16:06 UTC, F4ever commented
@vgorkavenko 
No pulse function just do `/pulse/` request to server that contains last pulse datetime.
All rest requests to this server just returns is last_puls_datetime expired or not

2023-10-04 16:14 UTC, vgorkavenko approved these changes

2023-10-04 16:15 UTC, vgorkavenko commented
> @vgorkavenko No pulse function just do `/pulse/` request to server that contains last pulse datetime. All rest requests to this server just returns is last_puls_datetime expired or not

Yes. Thanks for the explanation!

2023-10-05 12:46 UTC, skhomuti approved these changes

2023-10-05 12:46 UTC, skhomuti commented on src/modules/submodules/oracle_module.py
> +            # Do pulse only if no exceptions only
double "only" typo

2023-10-06 08:34 UTC, F4ever commented on src/modules/submodules/oracle_module.py
> +            # Do pulse only if no exceptions only
fixed

2023-10-23 09:43 UTC, merged