zero division fix
lidofinance/lido-oracle pull request #408
Opened 2023-10-09 02:39 UTC by F4ever

2023-10-23 14:22 UTC, rkolpakov approved these changes
lgtm

2023-10-24 05:43 UTC, skhomuti requested changes

2023-10-24 05:43 UTC, skhomuti commented on src/services/bunker_cases/abnormal_cl_rebase.py
> +        if normal_report_cl_rebase == 0:
add test pls

2023-10-24 11:55 UTC, F4ever commented on src/services/bunker_cases/abnormal_cl_rebase.py
> +        if normal_report_cl_rebase == 0:
Done!

2023-10-27 09:22 UTC, skhomuti approved these changes

2023-10-27 09:27 UTC, merged