split logging to stdout and stdout #57
lidofinance/lido-oracle pull request #63
Opened 2020-12-08 09:07 UTC by vsmelov

add init_log function

2020-12-09 08:31 UTC, ongrid requested changes
Add a single test that runs the app and asserts at least two messages : one STDOUT and one STDERR. Suitable place for such test is before interaction tests https://github.com/lidofinance/lido-oracle/blob/a56f7155fb68de275785e5b3ba105694ea7ea790/tests/test_oracle.py#L4

2020-12-11 11:13 UTC, onionglass commented
beacon.py ans contract.py also import logging

2020-12-11 11:48 UTC, ongrid requested changes
@onionglass could you please adapt this?

2020-12-15 07:27 UTC, Klyaus approved these changes

2020-12-15 07:29 UTC, ongrid approved these changes

2020-12-15 08:07 UTC, Klyaus approved these changes

2020-12-15 08:07 UTC, merged